=== itvieira/HIVacSim/HIVacSim/HIVacSim/HIVacSimData.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:sim="urn:HIVacSim"
            targetNamespace="urn:HIVacSim"
  elementFormDefault="qualified">
  <xsd:element name="HIVacSim">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Scenario" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Description" type="xsd:string" minOccurs="1" maxOccurs="1" />
              <xsd:element name="SimClock" type="xsd:string" minOccurs="1" maxOccurs="1" />
              <xsd:element name="RunDuration" type="xsd:integer" minOccurs="1" maxOccurs="1" />
              <xsd:element name="NumberOfRuns" type="xsd:integer" minOccurs="1" maxOccurs="1" />
              <xsd:element name="WarmUpType" type="xsd:string" minOccurs="1" maxOccurs="1" />
              <xsd:element name="WarmUp" type="xsd:integer" minOccurs="1" maxOccurs="1" />
              <xsd:element name="WarmUpMaxConcurrent" type="xsd:integer" minOccurs="1" maxOccurs="1" />
              <xsd:element name="WarmUpPrConcurrent" type="xsd:double" minOccurs="1" maxOccurs="1" />
              <xsd:element name="WarmUpInfected" type="sim:Stochastic" minOccurs="1" maxOccurs="1" />
              <xsd:element name="Speed" type="xsd:integer" minOccurs="1" maxOccurs="1" />
              <xsd:element name="MaxDelay" type="xsd:integer" minOccurs="1" maxOccurs="1" />
              <xsd:element name="Animation" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
              <xsd:element name="AutoSeed" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
              <xsd:element name="CustomSeed" type="xsd:unsignedInt" minOccurs="1" maxOccurs="1" />
              <xsd:element name="PLNumerical" type="xsd:integer" minOccurs="1" maxOccurs="1" />
              <xsd:element name="PLEstimate" type="xsd:integer" minOccurs="1" maxOccurs="1" />
              <xsd:element name="PLAlgorithm" type="xsd:double" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Disease" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1" />
              <xsd:element name="Male2Female" type="xsd:double" minOccurs="1" maxOccurs="1" />
              <xsd:element name="Female2Male" type="xsd:double" minOccurs="1" maxOccurs="1" />
              <xsd:element name="Male2Male" type="xsd:decimal" minOccurs="1" maxOccurs="1" />
              <xsd:element name="LifeInfection" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
              <xsd:element name="STDDuration" minOccurs="1" maxOccurs="1" type="sim:Stochastic"></xsd:element>
              <xsd:element name="AllowReinfection" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
              <xsd:element name="Mortality" type="xsd:double" minOccurs="1" maxOccurs="1" />
              <xsd:element name="LifeExpectancy" minOccurs="1" maxOccurs="1" type="sim:Stochastic"></xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Population" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Group" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Id" type="xsd:integer" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Topology" type="xsd:string" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Alpha" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Beta" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Radius" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Distance" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Degrees" type="xsd:integer" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Size" type="xsd:integer" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Age" type="sim:Stochastic" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="LifeExpectancy" type="sim:Stochastic" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="STDPrevalence" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="STDAge" type="sim:Stochastic" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="STDTest" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Female" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Male" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Homosexual" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="MaxConcurrent" type="xsd:integer" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="PrConcurrent" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="PrNewPartner" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="PrCasual" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="PrInternal" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="StbDuration" type="sim:Stochastic" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="StbTransitory" type="sim:Stochastic" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="StbContacts" type="sim:Stochastic" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="StbSafeSex" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="CslDuration" type="sim:Stochastic" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="CslContacts" type="sim:Stochastic" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="CslSafeSex" type="xsd:double" minOccurs="1" maxOccurs="1" />
                  </xsd:sequence>
                  <xsd:attribute name="Name" type="xsd:string" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="Count" type="xsd:integer" />
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="AdjMatrix" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Cell" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence></xsd:sequence>
                  <xsd:attribute name="Row" type="xsd:integer" />
                  <xsd:attribute name="Column" type="xsd:integer" />
                  <xsd:attribute name="Data" type="xsd:double" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="Rows" type="xsd:integer" />
            <xsd:attribute name="Columns" type="xsd:integer" />
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Vaccines" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Vaccine" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Id" type="xsd:integer" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Effectiveness" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Lifetime" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Length" type="xsd:integer" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="UsedBy" type="xsd:string" minOccurs="1" maxOccurs="1" />
                  </xsd:sequence>
                  <xsd:attribute name="Name" type="xsd:string" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="Count" type="xsd:integer" />
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Interventions" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Strategy" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Id" type="xsd:integer" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Active" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Strategy" type="xsd:string" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Groups" type="xsd:string" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Clock" type="xsd:integer" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Population" type="xsd:double" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="Vaccine" type="xsd:integer" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="HIVTested" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
                    <xsd:element name="HIVResult" type="xsd:string" minOccurs="1" maxOccurs="1" />
                  </xsd:sequence>
                  <xsd:attribute name="Name" type="xsd:string" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="Count" type="xsd:integer" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="Title" type="xsd:string" />
      <xsd:attribute name="by" type="xsd:string" />
      <xsd:attribute name="Version" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="Stochastic">
    <xsd:complexContent>
      <xsd:restriction base="xsd:anyType">
        <xsd:sequence>
          <xsd:element name="Distribution" type="xsd:string" />
          <xsd:element name="ParamOne" type="xsd:double" />
          <xsd:element name="ParamTwo" type="xsd:double" />
          <xsd:element name="ParamThree" type="xsd:double" />
          <xsd:element name="ParamFour" type="xsd:double" />
        </xsd:sequence>
      </xsd:restriction>
    </xsd:complexContent>
  </xsd:complexType>
</xsd:schema>

=== itvieira/HIVacSim/HIVacSim/HIVacSim/Example.xml
<?xml version="1.0" encoding="utf-8" ?>
<HIVacSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:HIVacSim" xsi:schemaLocation="urn:HIVacSim HIVacSimData.xsd"
	Title="Simulation Models for the Control of the Dynamics of HIV Infection Through Vaccination"
	by="Israel Vieira" Version="1.1">
	<!--Scenario's simulation settings definition.-->
	<Scenario>
		<Description>Testing HIVacSim Data File</Description>
		<SimClock>Month</SimClock>
		<RunDuration>120</RunDuration>
		<NumberOfRuns>2</NumberOfRuns>
		<WarmUpType>Traditional</WarmUpType>
		<WarmUp>24</WarmUp>
		<WarmUpMaxConcurrent>2</WarmUpMaxConcurrent>
		<WarmUpPrConcurrent>1.0</WarmUpPrConcurrent>
		<WarmUpInfected>
			<Distribution>Fixed</Distribution>
			<ParamOne>1</ParamOne>
			<ParamTwo>0</ParamTwo>
			<ParamThree>0</ParamThree>
			<ParamFour>0</ParamFour>
		</WarmUpInfected>
		<Speed>100</Speed>
		<MaxDelay>2000</MaxDelay>
		<Animation>false</Animation>
		<AutoSeed>true</AutoSeed>
		<CustomSeed>19650218</CustomSeed>
		<PLNumerical>500</PLNumerical>
		<PLEstimate>300</PLEstimate>
		<PLAlgorithm>0.50</PLAlgorithm>
	</Scenario>
	<!--Define the disease of interest to be simulated-->
	<Disease>
		<Name>HIV/AIDS</Name>
		<Male2Female>0.003</Male2Female>
		<Female2Male>0.002</Female2Male>
		<Male2Male>0.01</Male2Male>
		<LifeInfection>true</LifeInfection>
		<STDDuration>
			<Distribution>Fixed</Distribution>
			<ParamOne>0</ParamOne>
			<ParamTwo>0</ParamTwo>
			<ParamThree>0</ParamThree>
			<ParamFour>0</ParamFour>
		</STDDuration>
		<AllowReinfection>false</AllowReinfection>
		<Mortality>0.98</Mortality>
		<LifeExpectancy>
			<Distribution>Uniform</Distribution>
			<ParamOne>84</ParamOne>
			<ParamTwo>144</ParamTwo>
			<ParamThree>0</ParamThree>
			<ParamFour>0</ParamFour>
		</LifeExpectancy>
	</Disease>
	<!--Population Core Groups Definition-->
	<Population Count="3">
		<Group Name="Under 25 years old">
			<Id>1</Id>
			<Topology>Free</Topology>
			<Alpha>1.0</Alpha>
			<Beta>1.0</Beta>
			<Radius>6371.0</Radius>
			<Distance>1.0</Distance>
			<Degrees>3</Degrees>
			<Size>60</Size>
			<Age>
				<Distribution>Weibull</Distribution>
				<ParamOne>15.791</ParamOne>
				<ParamTwo>2.181</ParamTwo>
				<ParamThree>24.114</ParamThree>
				<ParamFour>0</ParamFour>
			</Age>
			<LifeExpectancy>
				<Distribution>Uniform</Distribution>
				<ParamOne>876</ParamOne>
				<ParamTwo>924</ParamTwo>
				<ParamThree>0</ParamThree>
				<ParamFour>0</ParamFour>
			</LifeExpectancy>
			<STDPrevalence>0.2</STDPrevalence>
			<STDAge>
				<Distribution>Uniform</Distribution>
				<ParamOne>0</ParamOne>
				<ParamTwo>60</ParamTwo>
				<ParamThree>0</ParamThree>
				<ParamFour>0</ParamFour>
			</STDAge>
			<STDTest>0.13</STDTest>
			<Female>0.57</Female>
			<Male>0.43</Male>
			<Homosexual>0.05</Homosexual>
			<MaxConcurrent>2</MaxConcurrent>
			<PrConcurrent>0.50</PrConcurrent>
			<PrNewPartner>0.69</PrNewPartner>
			<PrCasual>0.05</PrCasual>
			<PrInternal>0.90</PrInternal>
			<StbDuration>
				<Distribution>LogNormal</Distribution>
				<ParamOne>8.236</ParamOne>
				<ParamTwo>97.688</ParamTwo>
				<ParamThree>195.70</ParamThree>
				<ParamFour>0</ParamFour>
			</StbDuration>
			<StbTransitory>
				<Distribution>LogNormal</Distribution>
				<ParamOne>-0.169</ParamOne>
				<ParamTwo>41.453</ParamTwo>
				<ParamThree>66.952</ParamThree>
				<ParamFour>0</ParamFour>
			</StbTransitory>
			<StbContacts>
				<Distribution>LogNormal</Distribution>
				<ParamOne>-0.055</ParamOne>
				<ParamTwo>6.814</ParamTwo>
				<ParamThree>6.309</ParamThree>
				<ParamFour>0</ParamFour>
			</StbContacts>
			<StbSafeSex>0.125</StbSafeSex>
			<CslDuration>
				<Distribution>Geometric</Distribution>
				<ParamOne>0.238</ParamOne>
				<ParamTwo>0</ParamTwo>
				<ParamThree>0</ParamThree>
				<ParamFour>0</ParamFour>
			</CslDuration>
			<CslContacts>
				<Distribution>LogNormal</Distribution>
				<ParamOne>-0.111</ParamOne>
				<ParamTwo>7.516</ParamTwo>
				<ParamThree>7.121</ParamThree>
				<ParamFour>0</ParamFour>
			</CslContacts>
			<CslSafeSex>0.147</CslSafeSex>
		</Group>
		<Group Name="Married Couples">
			<Id>2</Id>
			<Topology>Circle</Topology>
			<Alpha>1.0</Alpha>
			<Beta>1.0</Beta>
			<Radius>6371.0</Radius>
			<Distance>1.0</Distance>
			<Degrees>3</Degrees>
			<Size>55</Size>
			<Age>
				<Distribution>Weibull</Distribution>
				<ParamOne>15.791</ParamOne>
				<ParamTwo>2.181</ParamTwo>
				<ParamThree>24.114</ParamThree>
				<ParamFour>0</ParamFour>
			</Age>
			<LifeExpectancy>
				<Distribution>Uniform</Distribution>
				<ParamOne>876</ParamOne>
				<ParamTwo>924</ParamTwo>
				<ParamThree>0</ParamThree>
				<ParamFour>0</ParamFour>
			</LifeExpectancy>
			<STDPrevalence>0.2</STDPrevalence>
			<STDAge>
				<Distribution>Uniform</Distribution>
				<ParamOne>0</ParamOne>
				<ParamTwo>60</ParamTwo>
				<ParamThree>0</ParamThree>
				<ParamFour>0</ParamFour>
			</STDAge>
			<STDTest>0.13</STDTest>
			<Female>0.57</Female>
			<Male>0.43</Male>
			<Homosexual>0.05</Homosexual>
			<MaxConcurrent>2</MaxConcurrent>
			<PrConcurrent>0.50</PrConcurrent>
			<PrNewPartner>1</PrNewPartner>
			<PrCasual>0.02</PrCasual>
			<PrInternal>0.90</PrInternal>
			<StbDuration>
				<Distribution>LogNormal</Distribution>
				<ParamOne>8.236</ParamOne>
				<ParamTwo>97.688</ParamTwo>
				<ParamThree>195.70</ParamThree>
				<ParamFour>0</ParamFour>
			</StbDuration>
			<StbTransitory>
				<Distribution>LogNormal</Distribution>
				<ParamOne>-0.169</ParamOne>
				<ParamTwo>41.453</ParamTwo>
				<ParamThree>66.952</ParamThree>
				<ParamFour>0</ParamFour>
			</StbTransitory>
			<StbContacts>
				<Distribution>LogNormal</Distribution>
				<ParamOne>-0.055</ParamOne>
				<ParamTwo>6.814</ParamTwo>
				<ParamThree>6.309</ParamThree>
				<ParamFour>0</ParamFour>
			</StbContacts>
			<StbSafeSex>0.125</StbSafeSex>
			<CslDuration>
				<Distribution>Geometric</Distribution>
				<ParamOne>0.238</ParamOne>
				<ParamTwo>0</ParamTwo>
				<ParamThree>0</ParamThree>
				<ParamFour>0</ParamFour>
			</CslDuration>
			<CslContacts>
				<Distribution>LogNormal</Distribution>
				<ParamOne>-0.111</ParamOne>
				<ParamTwo>7.516</ParamTwo>
				<ParamThree>7.121</ParamThree>
				<ParamFour>0</ParamFour>
			</CslContacts>
			<CslSafeSex>0.147</CslSafeSex>
		</Group>
		<Group Name="Others">
			<Id>3</Id>
			<Topology>Sphere</Topology>
			<Alpha>1.0</Alpha>
			<Beta>1.0</Beta>
			<Radius>6371.0</Radius>
			<Distance>1.0</Distance>
			<Degrees>3</Degrees>
			<Size>50</Size>
			<Age>
				<Distribution>Weibull</Distribution>
				<ParamOne>15.791</ParamOne>
				<ParamTwo>2.181</ParamTwo>
				<ParamThree>24.114</ParamThree>
				<ParamFour>0</ParamFour>
			</Age>
			<LifeExpectancy>
				<Distribution>Uniform</Distribution>
				<ParamOne>876</ParamOne>
				<ParamTwo>924</ParamTwo>
				<ParamThree>0</ParamThree>
				<ParamFour>0</ParamFour>
			</LifeExpectancy>
			<STDPrevalence>0.2</STDPrevalence>
			<STDAge>
				<Distribution>Uniform</Distribution>
				<ParamOne>0</ParamOne>
				<ParamTwo>60</ParamTwo>
				<ParamThree>0</ParamThree>
				<ParamFour>0</ParamFour>
			</STDAge>
			<STDTest>0.13</STDTest>
			<Female>0.57</Female>
			<Male>0.43</Male>
			<Homosexual>0.1</Homosexual>
			<MaxConcurrent>2</MaxConcurrent>
			<PrConcurrent>0.50</PrConcurrent>
			<PrNewPartner>0.70</PrNewPartner>
			<PrCasual>0.02</PrCasual>
			<PrInternal>0.90</PrInternal>
			<StbDuration>
				<Distribution>LogNormal</Distribution>
				<ParamOne>8.236</ParamOne>
				<ParamTwo>97.688</ParamTwo>
				<ParamThree>195.70</ParamThree>
				<ParamFour>0</ParamFour>
			</StbDuration>
			<StbTransitory>
				<Distribution>LogNormal</Distribution>
				<ParamOne>-0.169</ParamOne>
				<ParamTwo>41.453</ParamTwo>
				<ParamThree>66.952</ParamThree>
				<ParamFour>0</ParamFour>
			</StbTransitory>
			<StbContacts>
				<Distribution>LogNormal</Distribution>
				<ParamOne>-0.055</ParamOne>
				<ParamTwo>6.814</ParamTwo>
				<ParamThree>6.309</ParamThree>
				<ParamFour>0</ParamFour>
			</StbContacts>
			<StbSafeSex>0.125</StbSafeSex>
			<CslDuration>
				<Distribution>Geometric</Distribution>
				<ParamOne>0.238</ParamOne>
				<ParamTwo>0</ParamTwo>
				<ParamThree>0</ParamThree>
				<ParamFour>0</ParamFour>
			</CslDuration>
			<CslContacts>
				<Distribution>LogNormal</Distribution>
				<ParamOne>-0.111</ParamOne>
				<ParamTwo>7.516</ParamTwo>
				<ParamThree>7.121</ParamThree>
				<ParamFour>0</ParamFour>
			</CslContacts>
			<CslSafeSex>0.147</CslSafeSex>
		</Group>
	</Population>
	<!--Population interaction matrix, digraph adjacency matrix-->
	<AdjMatrix Rows="3" Columns="3">
		<Cell Row="0" Column="0" Data="0.0" />
		<Cell Row="0" Column="1" Data="0.5" />
		<Cell Row="0" Column="2" Data="0.5" />
		<Cell Row="1" Column="0" Data="0.5" />
		<Cell Row="1" Column="1" Data="0.0" />
		<Cell Row="1" Column="2" Data="0.5" />
		<Cell Row="2" Column="0" Data="0.5" />
		<Cell Row="2" Column="1" Data="0.5" />
		<Cell Row="2" Column="2" Data="0.0" />
	</AdjMatrix>
	<!-- Preventive vaccine interventions-->
	<Vaccines Count="1">
		<Vaccine Name="ALVAC">
			<Id>1</Id>
			<Effectiveness>0.50</Effectiveness>
			<Lifetime>false</Lifetime>
			<Length>48</Length>
			<UsedBy>1</UsedBy>
		</Vaccine>
	</Vaccines>
	<!-- Intervention strategies-->
	<Interventions Count="1">
		<Strategy Name="Everyone safe">
			<Id>1</Id>
			<Active>false</Active>
			<Strategy>AllGroups</Strategy>
			<Groups></Groups>
			<Clock>1</Clock>
			<Population>0.6</Population>
			<Vaccine>1</Vaccine>
			<HIVTested>false</HIVTested>
			<HIVResult>NotImportant</HIVResult>
		</Strategy>
	</Interventions>
</HIVacSim>

=== itvieira/HIVacSim/HIVacSim/Data/SingleGroupScenario.xml
<?xml version="1.0" encoding="utf-8"?>
<HIVacSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="urn:HIVacSim" xsi:schemaLocation="urn:HIVacSim HIVacSimData.xsd" 
          Title="Simulation Models for the Control of the Dynamics of HIV Infection Through Vaccination" 
          by="Israel Vieira" 
          Version="1.7">
  <!--Scenario's simulation settings definition.-->
  <Scenario>
    <Description>Brazilian Population Sexual Behaviour and Perceptions of HIV/AIDS Survey, July 1999</Description>
    <SimClock>Month</SimClock>
    <RunDuration>144</RunDuration>
    <NumberOfRuns>10</NumberOfRuns>
    <WarmUpType>Traditional</WarmUpType>
    <WarmUp>24</WarmUp>
    <WarmUpMaxConcurrent>2</WarmUpMaxConcurrent>
    <WarmUpPrConcurrent>0.5</WarmUpPrConcurrent>
    <WarmUpInfected>
      <Distribution>Average</Distribution>
      <ParamOne>1</ParamOne>
      <ParamTwo>0</ParamTwo>
      <ParamThree>0</ParamThree>
      <ParamFour>0</ParamFour>
    </WarmUpInfected>
    <Speed>100</Speed>
    <MaxDelay>2000</MaxDelay>
    <Animation>false</Animation>
    <AutoSeed>true</AutoSeed>
    <CustomSeed>19650218</CustomSeed>
    <PLNumerical>500</PLNumerical>
    <PLEstimate>400</PLEstimate>
    <PLAlgorithm>0.13</PLAlgorithm>
  </Scenario>
  <!--Define the disease of interest to be simulated-->
  <Disease>
    <Name>HIV/AIDS</Name>
    <Male2Female>0.003</Male2Female>
    <Female2Male>0.002</Female2Male>
    <Male2Male>0.01</Male2Male>
    <LifeInfection>true</LifeInfection>
    <STDDuration>
      <Distribution>Average</Distribution>
      <ParamOne>0</ParamOne>
      <ParamTwo>0</ParamTwo>
      <ParamThree>0</ParamThree>
      <ParamFour>0</ParamFour>
    </STDDuration>
    <AllowReinfection>false</AllowReinfection>
    <Mortality>0.95</Mortality>
    <LifeExpectancy>
      <Distribution>Weibull</Distribution>
      <ParamOne>0</ParamOne>
      <ParamTwo>126.12</ParamTwo>
      <ParamThree>2.38</ParamThree>
      <ParamFour>0</ParamFour>
    </LifeExpectancy>
  </Disease>
  <!--Population Core Groups Definition-->
  <Population Count="1">
    <Group Name="Brazil">
      <Id>1</Id>
      <Topology>Sphere</Topology>
      <Alpha>0.226066111496547</Alpha>
      <Beta>1</Beta>
      <Radius>6378</Radius>
      <Distance>1568.42532234911</Distance>
      <Degrees>3</Degrees>
      <Size>3324</Size>
      <Age>
        <Distribution>Weibull</Distribution>
        <ParamOne>181.47</ParamOne>
        <ParamTwo>267.95</ParamTwo>
        <ParamThree>1.46</ParamThree>
        <ParamFour>0</ParamFour>
      </Age>
      <LifeExpectancy>
        <Distribution>Average</Distribution>
        <ParamOne>840</ParamOne>
        <ParamTwo>0</ParamTwo>
        <ParamThree>0</ParamThree>
        <ParamFour>0</ParamFour>
      </LifeExpectancy>
      <STDPrevalence>0.007</STDPrevalence>
      <STDAge>
        <Distribution>Weibull</Distribution>
        <ParamOne>0.13</ParamOne>
        <ParamTwo>47.78</ParamTwo>
        <ParamThree>1.36</ParamThree>
        <ParamFour>0</ParamFour>
      </STDAge>
      <STDTest>0.28</STDTest>
      <Female>0.55</Female>
      <Male>0.45</Male>
      <Homosexual>0.05</Homosexual>
      <MaxConcurrent>5</MaxConcurrent>
      <PrConcurrent>0.11</PrConcurrent>
      <PrNewPartner>0.82</PrNewPartner>
      <PrCasual>0.18</PrCasual>
      <PrInternal>1</PrInternal>
      <StbDuration>
        <Distribution>Weibull</Distribution>
        <ParamOne>0</ParamOne>
        <ParamTwo>141.36</ParamTwo>
        <ParamThree>1.1</ParamThree>
        <ParamFour>0</ParamFour>
      </StbDuration>
      <StbTransitory>
        <Distribution>Gamma</Distribution>
        <ParamOne>0</ParamOne>
        <ParamTwo>20.2</ParamTwo>
        <ParamThree>1.06</ParamThree>
        <ParamFour>0</ParamFour>
      </StbTransitory>
      <StbContacts>
        <Distribution>Gamma</Distribution>
        <ParamOne>0</ParamOne>
        <ParamTwo>4.83</ParamTwo>
        <ParamThree>1.41</ParamThree>
        <ParamFour>0</ParamFour>
      </StbContacts>
      <StbSafeSex>0.18</StbSafeSex>
      <CslDuration>
        <Distribution>InvNormal</Distribution>
        <ParamOne>-2.44</ParamOne>
        <ParamTwo>14.49</ParamTwo>
        <ParamThree>49.6</ParamThree>
        <ParamFour>0</ParamFour>
      </CslDuration>
      <CslContacts>
        <Distribution>Gamma</Distribution>
        <ParamOne>0</ParamOne>
        <ParamTwo>5.02</ParamTwo>
        <ParamThree>1.5</ParamThree>
        <ParamFour>0</ParamFour>
      </CslContacts>
      <CslSafeSex>0.42</CslSafeSex>
    </Group>
  </Population>
  <!--Population interaction, digraph adjacency matrix-->
  <AdjMatrix Rows="1" Columns="1">
    <Cell Row="0" Column="0" Data="0" />
  </AdjMatrix>
  <!--Preventive vaccine interventions-->
  <Vaccines Count="3">
    <Vaccine Name="Vaccine 25%">
      <Id>1</Id>
      <Effectiveness>0.25</Effectiveness>
      <Lifetime>true</Lifetime>
      <Length>0</Length>
      <UsedBy>1,4,7,10</UsedBy>
    </Vaccine>
    <Vaccine Name="Vaccine 50%">
      <Id>2</Id>
      <Effectiveness>0.5</Effectiveness>
      <Lifetime>true</Lifetime>
      <Length>0</Length>
      <UsedBy>2,5,8,11</UsedBy>
    </Vaccine>
    <Vaccine Name="Vaccine 75%">
      <Id>3</Id>
      <Effectiveness>0.75</Effectiveness>
      <Lifetime>true</Lifetime>
      <Length>0</Length>
      <UsedBy>3,6,9,12</UsedBy>
    </Vaccine>
  </Vaccines>
  <!--Intervention strategies-->
  <Interventions Count="12">
    <Strategy Name="Coverage 25% - Vaccine 25%">
      <Id>1</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>0.25</Population>
      <Vaccine>1</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 25% - Vaccine 50%">
      <Id>2</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>0.25</Population>
      <Vaccine>2</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 25% - Vaccine 75%">
      <Id>3</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>0.25</Population>
      <Vaccine>3</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 50% - Vaccine 25%">
      <Id>4</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>0.5</Population>
      <Vaccine>1</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 50% - Vaccine 50%">
      <Id>5</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>0.5</Population>
      <Vaccine>2</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 50% - Vaccine 75%">
      <Id>6</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>0.5</Population>
      <Vaccine>3</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 75% - Vaccine 25%">
      <Id>7</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>0.75</Population>
      <Vaccine>1</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 75% - Vaccine 50%">
      <Id>8</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>0.75</Population>
      <Vaccine>2</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 75% - Vaccine 75%">
      <Id>9</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>0.75</Population>
      <Vaccine>3</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 100% - Vaccine 25%">
      <Id>10</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>1</Population>
      <Vaccine>1</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 100% - Vaccine 50%">
      <Id>11</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>1</Population>
      <Vaccine>2</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
    <Strategy Name="Coverage 100% - Vaccine 75%">
      <Id>12</Id>
      <Active>false</Active>
      <Strategy>AllGroups</Strategy>
      <Groups />
      <Clock>1</Clock>
      <Population>1</Population>
      <Vaccine>3</Vaccine>
      <HIVTested>false</HIVTested>
      <HIVResult>HIVNegative</HIVResult>
    </Strategy>
  </Interventions>
</HIVacSim>
